modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
modId="heracles"
version="${file.jarVersion}"
displayName="Heracles"

description='''
'''

[[dependencies.heracles]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"

[[dependencies.heracles]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"
